# Generated by Django 4.2.5 on 2023-10-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='image',
            field=models.ImageField(default='C:/Users/adin/Downloads/My_Photo.jpeg', upload_to='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artifact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
