# Generated by Django 4.2.5 on 2023-10-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_artifact_image_alter_artifact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='video',
            field=models.FileField(blank=True, default='artifact/videos/default-video.mp4', upload_to='artifact/videos'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='image',
            field=models.ImageField(blank=True, default='artifact/images/default-image.jpg', upload_to='artifact/images'),
        ),
    ]
