# Generated by Django 4.2.5 on 2023-10-06 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_artifact_artifact_category_artifact_artifact_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='status',
            field=models.CharField(blank=True, default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 6, 6, 11, 37, 234357, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='created_by',
            field=models.CharField(default='System', max_length=100),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='modified_by',
            field=models.CharField(default='System', max_length=100),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='published_date',
            field=models.DateField(default=datetime.date(2023, 10, 6)),
        ),
    ]
